CREATE TABLE CLIENTE(
ID_CLIENTE NUMBER(3) CONSTRAINT CL_IDC_PK PRIMARY KEY,
APATERNO VARCHAR2(35) CONSTRAINT CL_AP_NN NOT NULL,
AMATERNO VARCHAR2(35),
NOMBRE VARCHAR2(50) CONSTRAINT CL_NOM_NN NOT NULL,
EDAD NUMBER(2) CONSTRAINT CL_ED_NN NOT NULL,
TELEFONO NUMBER(10),
CORREO VARCHAR (40),
DIRECCION VARCHAR(40) CONSTRAINT CL_DIR_NN NOT NULL,
MUNICIPIO VARCHAR(40) CONSTRAINT CL_MUN_NN NOT NULL
);

CREATE TABLE EMPLEADO(
ID_EMPLEADO NUMBER(3) CONSTRAINT EM_IDE_PK PRIMARY KEY,
APATERNO VARCHAR2(35) CONSTRAINT EM_AP_NN NOT NULL,
AMATERNO VARCHAR2(35),
NOMBRE VARCHAR2(50) CONSTRAINT EM_NOM_NN NOT NULL,
EDAD NUMBER(2) CONSTRAINT EM_ED_NN NOT NULL,
TELEFONO NUMBER(10),
CORREO VARCHAR (40) CONSTRAINT EM_COR_NN NOT NULL,
DIRECCION VARCHAR(40) CONSTRAINT EM_DIR_NN NOT NULL,
MUNICIPIO VARCHAR(40) CONSTRAINT EM_MUN_NN NOT NULL,
SALARIO NUMBER(5) CONSTRAINT EM_SAL_NN NOT NULL
);

CREATE TABLE MASCOTA(
ID_MASCOTA NUMBER(3) CONSTRAINT MAS_IDM_PK PRIMARY KEY,
NOMBRE VARCHAR(30) CONSTRAINT MAS_NOM_NN NOT NULL,
RAZA VARCHAR(30) CONSTRAINT MAS_RZ_NN NOT NULL,
EDAD NUMBER(2) CONSTRAINT MAS_ED_NN NOT NULL,
PESO NUMBER(3) CONSTRAINT MAS_PS_NN NOT NULL
);

CREATE TABLE CITA(
ID_CLIENTE NUMBER(3),
ID_EMPLEADO NUMBER(3),
ID_MASCOTA NUMBER(3),
ID_CITA NUMBER(3),
FECHA DATE CONSTRAINT CT_FCH_NN NOT NULL,
CONSTRAINT CT_IDCT_PK PRIMARY KEY (ID_CITA),
CONSTRAINT CT_IDC_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
CONSTRAINT CT_IDE_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO(ID_EMPLEADO),
CONSTRAINT CT_IDM_FK FOREIGN KEY (ID_MASCOTA) REFERENCES MASCOTA(ID_MASCOTA)
);

CREATE TABLE VETERINARIO(
ID_VETERINARIO NUMBER(3) CONSTRAINT VT_IDVT_PK PRIMARY KEY,
APATERNO VARCHAR2(35) CONSTRAINT VT_AP_NN NOT NULL,
AMATERNO VARCHAR2(35),
NOMBRE VARCHAR2(50) CONSTRAINT VT_NOM_NN NOT NULL,
EDAD NUMBER(2) CONSTRAINT VT_ED_NN NOT NULL,
TELEFONO NUMBER(10) CONSTRAINT VT_TEL_NN NOT NULL,
CORREO VARCHAR (40) CONSTRAINT VT_COR_NN NOT NULL,
DIRECCION VARCHAR(40) CONSTRAINT VT_DIR_NN NOT NULL,
MUNICIPIO VARCHAR(40) CONSTRAINT VT_MUN_NN NOT NULL,
SALARIO NUMBER(5) CONSTRAINT VT_SAL_NN NOT NULL
);

CREATE TABLE CONSULTA(
ID_CITA NUMBER(3),
ID_VETERINARIO NUMBER(3),
ID_CONSULTA NUMBER(3),
CONSTRAINT CN_CN_PK PRIMARY KEY(ID_CONSULTA),
CONSTRAINT CN_CT_FK FOREIGN KEY (ID_CITA) REFERENCES CITA(ID_CITA), 
CONSTRAINT CN_VT_FK FOREIGN KEY (ID_VETERINARIO) REFERENCES VETERINARIO(ID_VETERINARIO)
);
